<?php

        $apiKey="rzp_test_f5LG96lHutW5f1";

        include 'conn.php';
        session_start();
        $sid=$_SESSION['ses_id'];
        $cusamount=$_GET['amount'];
        $odr_id=$_GET['odr_id'];
        $cust_select = "SELECT cust_id FROM tbl_customer WHERE login_id='$_SESSION[ses_id]'";
        $cust_result = mysqli_query($con, $cust_select);
        $cust_fetch = mysqli_fetch_array($cust_result);
        $custid = $cust_fetch['cust_id']; //customer id

        $query="SELECT tbl_payments.* FROM tbl_payments WHERE cust_id='$custid' AND order_id='$odr_id' ORDER BY pay_id DESC LIMIT 1";
        $result=mysqli_query($con,$query);

        while ($row = mysqli_fetch_assoc($result)) {

            $pid=$row['pay_id'];
            $orderid=$row['order_id'];
            $cust_id=$row['cust_id'];
        }

        //$totalamount=$amount + $cusamount;  

?>

<form action="razor_pay_action.php?pid=<?php echo $pid ?>&&oid=<?php echo $orderid ?>&&cusid=<?php echo $cust_id ?>" method="POST">

<script

    src="https://checkout.razorpay.com/v1/checkout.js"

    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys

    data-amount="<?php echo $cusamount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.

    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account

    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.

    data-buttontext="Pay"

    data-name="Home-Foodi"//project name

    data-description="Homely Food For you "

    data-image=""

    data-prefill.name=""

    data-prefill.email=""

    data-theme.color="#F37254"

></script>

<input type="hidden" custom="Hidden Element" name="hidden">

</form>

 

<!--style>

.razorpay-payment-button { display:none; }

</style><script type="text/javascript">

  $(document).ready(function(){

    $('.razorpay-payment-button').click();

 

});

</script-->